# Site settings
title: Pachira
description: >
  Webpage for Senior Design 20/21 Team Pachira
baseurl: "/pachira" # the subpath of your site, e.g. /blog/
url: "https://rebeccc.github.io" # the base hostname & protocol for your site

# Build settings
theme: jekyll-theme-slate
